# Generated by Django 5.0.7 on 2024-07-17 02:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "interested",
                    models.CharField(
                        choices=[
                            ("attic", "Attic"),
                            ("hvac_check_up", "HVAC Check Up"),
                            ("hybrid_heating_system", "Hybrid Heating System"),
                            ("heat_pump", "Heat Pump"),
                            ("gas_bill_savings", "Gas Bill Savings"),
                            ("electricity_bill_savings", "Electricity Bill Savings"),
                            ("free_ac", "Free AC"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(
                        choices=[
                            ("weaverecohome", "Weaverecohome.ca"),
                            ("bought_lead", "Bought Lead"),
                            ("morocco", "Morocco"),
                            ("c_social_ext", "C Social (EXT)"),
                            ("c_social_int", "C Social (INT)"),
                            ("call_center_weh_d", "Call Center - WEH - D"),
                            ("current_customer", "Current Customer"),
                            ("dealer", "Dealer"),
                            ("door_to_door", "Door to Door"),
                            ("email", "Email"),
                            ("facebook_cmc", "Facebook (CMC)"),
                            ("facebook_da", "Facebook (DA)"),
                            ("facebook_vu", "Facebook (VU)"),
                            ("follow_up_appointment", "Follow Up Appointment"),
                            ("google", "Google"),
                            ("instagram", "Instagram"),
                            ("promo", "Promo"),
                            ("referral", "Referral"),
                            ("sms", "SMS"),
                            ("website", "Website"),
                            ("youtube", "Youtube"),
                            ("other", "Other"),
                            ("online_da", "Online (DA)"),
                        ],
                        max_length=100,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift_start_time", models.TimeField()),
                ("shift_end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="aicaller.lead",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="aicaller.salesagent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_caller", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "call_type",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=50,
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_chats",
                        to="aicaller.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="VoiceMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "voice_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="aicaller.voicechat",
                    ),
                ),
            ],
        ),
    ]
