# Generated by Django 5.0.7 on 2024-07-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aicaller", "0003_voicechat_call_id_voicechat_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicechat",
            name="call_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="voicechat",
            name="session_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
