# Generated by Django 5.0.7 on 2024-07-18 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aicaller", "0004_alter_voicechat_call_id_alter_voicechat_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicechat",
            name="lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voice_chats",
                to="aicaller.lead",
            ),
        ),
    ]
