# Generated by Django 5.0.7 on 2024-07-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aicaller", "0006_rename_session_id_voicemessage_call_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicemessage",
            name="call_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
