# Generated by Django 5.0.7 on 2024-07-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aicaller", "0007_alter_voicemessage_call_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicemessage",
            name="call_id",
            field=models.CharField(max_length=255),
        ),
    ]
