# Generated by Django 5.0.7 on 2024-07-20 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aicaller", "0008_alter_voicemessage_call_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VoiceChat",
            new_name="VoiceCall",
        ),
    ]
